server:
  port: 8888
cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://erudio.com.br
file:
  upload-dir: /Users/AGAPESISTEMAS/Documents/Projetos/Arquivos/upload
security:
  jwt:
    token:
      secret-key: 53ccr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
springdoc:
  pathsToMach:
    - /auth/**/
    - /api/**/
  swagger-ui:
    use-root-path: true


