server:
  port: 8080
cors:
  originPatterns: http://localhost:5173,http://localhost:80,http://localhost:8080,https://erudio.com.br
file:
  upload-dir: /Users/Isac - Agape/Documents/upload
security:
  jwt:
    token:
      secret-key: 53ccr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/curso_spring?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        time_zone: America/Sao_Paulo
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
springdoc:
  pathsToMach:
    - /auth/**
    - /api/**/
  swagger-ui:
    use-root-path: true
    path: /swagger

logging:
  level:
    root: INFO


