cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://erudio.com.br
security:
  jwt:
    token:
      secret-key: 53ccr37
      expire-length: 3600000
spring:
  datasource:
    dbcp2:
      driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/api_spring?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
springdoc:
  pathsToMach:
    - /auth/**/
    - /api/**/
  swagger-ui:
    use-root-path: true


