name: Continuous Integration with Github Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Debug Temp Script
      run: cat /home/runner/work/_temp/b109c793-42a5-41c2-a329-1ab4aa60b8e7.sh
      
    - name: Build Application JAR
      working-directory: ./
      run: |
        - pwd
        - mvn clean package

    - name: Docker Compose Build
      working-directory: ./API-with-spring-boot
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/aula_api_spring:latest ${{ secrets.DOCKER_USERNAME }}/aula_api_spring:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/aula_api_spring:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/aula_api_spring:latest
